### ISSUE TITLE
Release a new version with SPM support

### ISSUE THREAD

**Issue by RomanPodymov** [Skyvive/Swiftstraints#20]
Hello.
Thank you for Swiftstraints.
I know that in #19 @emirandm added SPM support. Could you please release a new version with this feature?

**Comment by bradhilton** [comment]
To release a new version I don't believe I have to do anything, I think we just update the Package.swift file, right?

**Comment by bradhilton** [comment]
@RomanPodymov do I need to tag it or create a GitHub release?

**Comment by RomanPodymov** [comment]
Hello @bradhilton 
Adding a new tag is enough.

**Comment by bradhilton** [comment]
@RomanPodymov K I just created a new release / added a tag. Let me know if that works for you.

**Comment by RomanPodymov** [comment]
Hello @bradhilton 
Many thanks. Could you please update https://github.com/Skyvive/Swiftstraints/blob/master/Swiftstraints.podspec as well?

**Comment by bradhilton** [comment]
@RomanPodymov Done

**Comment by RomanPodymov** [comment]
Hello @bradhilton 
Getting **CocoaPods could not find compatible versions for pod "Swiftstraints"** with **pod 'Swiftstraints', '5.2.0'**. Did you run **pod trunk push**?
