### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [Skyvive/Swiftstraints#5]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by bradhilton** [comment]
I plan on updating it for Swift 3 soon. Sorry about the delay!

**Comment by yonaskolb** [comment]
Any updates on this?

**Comment by bradhilton** [comment]
@lfarah @yonaskolb Updated to Swift 3 and pushed to the CocoaPods trunk. Let me know if you have any other issues. Thanks.

**Comment by lfarah** [comment]
Hey @bradhilton, thanks for taking time and doing this. You're awesome! 🎉
